CREATE TABLE Users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(30) NOT NULL UNIQUE,
    name varchar(30),
    email varchar(40) NOT NULL UNIQUE
);

CREATE TABLE Movies (
    id int GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
    title varchar(100) UNIQUE NOT NULL,
    poster_path varchar(200)
);